### ISSUE TITLE
Technologies to Utilize

### ISSUE THREAD

**Issue by indigocarmen** [climatepatch/carbonsource#4]
We need to get some technology guidelines laid out. So far the only pinned down technology is MySQL. Everything else is open. 

Web Scrapers: Scrappy? 
Data Visualization: Neo4j @gigerbytes and I spoke on this. Seems like a solid solution to visualize relationships in data
Web Development: Personally I am familiar with basic front end stuff, but I see in the survey a lot of folks are familiar with C# and .Net. What are we thinking here?

**Comment by calveym** [comment]
Tech has been decided, we are going with Rails, ActiveRecord and Postgres.
